service: habi-test-python
frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-offline

custom:
  TimeOut: 30
  stage: ${sls:stage}

  HOST: ${env:HOST}
  USER: ${env:USER}
  PASS: ${env:PASS}
  SCHEMA: ${env:SCHEMA}
  PORT: ${env:PORT}

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, "dev"}
  timeout: ${self:custom.TimeOut}

functions:
  Property:
    name: ${self:service}-Property-${self:custom.stage}
    handler: handlers/PropertyHandler.get_property
    timeout: ${self:custom.TimeOut}
    events:
      - http:
          path: /get-property
          method: get

  BlockOperation:
    name: ${self:service}-Block-Operation-${self:custom.stage}
    handler: handlers/BlockNumberHandler.block_operation
    timeout: ${self:custom.TimeOut}
    events:
      - http:
          path: /block-operation
          method: post
